name: blueprint
version: '0.1.0.0'
category: Other
author: Bradley Hardy
maintainer: bch29@cam.ac.uk
copyright: Bradley Hardy
license: BSD3
github: bch29/blueprint
extra-source-files:
- README.md
library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - base >=4.7 && <5
  - text
  - bytestring
  - containers
  - uuid-types
  - scientific
  - time
  - lens
  - singletons
  - aeson >=1.2 && <2.0
  - case-insensitive >=1.2 && <2
  - profunctors >=5.2 && <6
  - product-profunctors >=0.8 && <1
  - typemap
# tests:
#   blueprint-test:
#     main: Spec.hs
#     source-dirs: test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - base
#     # - blueprint
