name:                blueprint-opaleye
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/bch29/blueprint-opaleye#readme
license:             BSD3
author:              Bradley Hardy
maintainer:          bch29@cam.ac.uk
copyright:           Bradley Hardy
category:            Other
extra-source-files:
- README.md

library:
  source-dirs:      src

  ghc-options: -Wall

  dependencies:
    - base >= 4.7 && < 5
  
    - scientific
    - text
    - time
    - uuid-types
    - case-insensitive
  
    - singletons
    - profunctors
    - product-profunctors
    - lens
  
    - opaleye
  
    - typemap
    - blueprint

tests:
  blueprint-opaleye-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - blueprint
    - blueprint-opaleye
